### ISSUE TITLE
Including bootstrap directly

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/wvu-design-system#16]
Why include bootstrap directly in the project and just not as a package.json dependency?

**Comment by adamjohnson** [comment]
2fde51602bd2541af5471619bc1234752457a0aa is a related commit.

Also, might want to consider changing:

```json
"dependencies": {
   "bootstrap": "4.2"
}
```

to:

```json
"dependencies": {
   "bootstrap": "4.x.x"
}
```

or 

```json
"dependencies": {
   "bootstrap": "^4.2"
}
```

More on semver in npm: https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

**Comment by zeroedin** [comment]
I would use 

```
"dependencies": {
   "bootstrap": "^4.2"
}
```

**Comment by adamjohnson** [comment]
According to the [Semver Calculator](https://semver.npmjs.com/), this will lock the dependency to only update to patch releases.

> Patch releases: 1.0 or 1.0.x or ~1.0.4
Minor releases: 1 or 1.x or ^1.0.4
Major releases: * or x

I'd personally go with `^4.2` because we have traditionally been horrible with updating version numbers. I will leave the decision up to @adamglenn.
