### ISSUE TITLE
Profile page Office location icon different in other pages

### ISSUE THREAD

**Issue by mr0151** [wvuweb/wvu-design-system#238]
Profile page location icon reflecting as a telephone in other pages.

Attaching below is the screenshot of the same.

![image](https://user-images.githubusercontent.com/58947254/74177204-45ef1580-4c07-11ea-9a33-67dae471ceb0.png)

**Comment by adamjohnson** [comment]
Looks like this bug is in the [featurettes profiles](https://github.com/wvuweb/wvu-design-system/blob/master/views/includes/_wvu-featurettes__profiles.html#L136) partial on line 136. The class should change from `fa-phone` to `fa-building`.

When fixing this, one should definitely check/test lines 132-137.
